service: user-profile-api
frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: false
  # path: dist/apps/user-profile-api
  custom:
    enable_optimize:
      local: false

provider:
  name: aws
  region: undefined
  endpointType: undefined
  runtime: nodejs10.x

custom:
  serverless-offline:
    port: 4000

functions:
  user-profile-api:
    handler: src/handler.gqlRequestHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
    logRetentionInDays: 1

