projects:
  UserManagementAPI:
    schemaPath: graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: graphql
        region: us-east-2
        apiId: 7lpbshs63fdexgry5jph56i4xm
        maxDepth: 2
extensions:
  amplify:
    version: 3
