service: lambdas
frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  elasticWriter:
    name: elastic_writer
    handler: elasticWriter.handler