service: lambdas
frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

#There is probably a more evolveable way to package those lambdas
functions:
  elasticWriter:
    name: elastic_writer
    handler: elasticWriter/elasticWriter.handler

  mapsService:
    name: maps_service
    handler: maps/lambdaEndpoints.handler