service: user

plugins:
  - serverless-webpack
  - serverless-appsync-plugin
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: us-east-1
  timeout: 120
  stage: ${opt:stage, "dev"}
  environment:
    USER_TABLE: users_${opt:stage, "dev"}
    MAP_BOX_API_KEY: ${opt:mapBoxApiKey, ""}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - usersTable
          - Arn

functions:
  userService:
    handler: src/lambda/UserServiceHandler.handler
  graphql:
    handler: src/graphql/graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

custom:
  appSync:
    name: ${self:service}_${self:provider.stage}
    authenticationType: API_KEY
    mappingTemplates:
      - dataSource: UserService
        type: Query
        field: getUsers
        request: "getUsers-request.vtl"
        response: "getUsers-response.vtl"
      - dataSource: UserService
        type: Mutation
        field: addUser
        request: "addUser-request.vtl"
        response: "addUser-response.vtl"
      - dataSource: UserService
        type: Mutation
        field: updateUser
        request: "updateUser-request.vtl"
        response: "updateUser-response.vtl"
      - dataSource: UserService
        type: Mutation
        field: deleteUser
        request: "deleteUser-request.vtl"
        response: "deleteUser-response.vtl"
    dataSources:
      - type: AWS_LAMBDA
        name: UserService
        description: 'Lambda UserService DataSource'
        config:
          functionName: userService
  dynamodb:
    stages:
      - test
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users_${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5