service:
  name: superformula-fs
  publish: false

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-appsync-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
