service: marcelinosf

plugins:
  - serverless-plugin-typescript

custom:
  appName: marcelinosf

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

functions:
  address:
    name: ${self:custom.appName}_address_handler
    handler: address.handler