AWSTemplateFormatVersion: 2010-09-09
Description: >-
  superformula-user-api

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs10.x
    Timeout: 180
    Environment:
      Variables:
        DYNAMO_TABLE: !Ref DynamoDBUserTable
        DB_ENDPOINT: http://dynamodb.us-east-2.amazonaws.com
        REGION_NAME: us-east-2

Resources:
#DynamoDB
  DynamoDBUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: sf-users
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "name-idx"
          KeySchema:
            - AttributeName: "name"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: "NEW_IMAGE"

  DynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: appsync-dynamodb-role
      ManagedPolicyArns:
        - Ref: AppSyncDynamoDBPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com
    DependsOn:
      - AppSyncDynamoDBPolicy

  AppSyncDynamoDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy to allow AWS AppSync to access the tables created by this template.
      Path: /appsync/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
            Resource: !Join [ "", [ !GetAtt DynamoDBUserTable.Arn, "*" ] ]

#ElasticSearch
  ElasticSearchUserDomain:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
      DomainName: sf-users
      ElasticsearchClusterConfig:
        InstanceCount: '1'
        InstanceType: t2.small.elasticsearch
      ElasticsearchVersion: 7.7
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp2

  ElasticSearchSyncLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sf-users-dependencies
      ContentUri: functions/layers
      CompatibleRuntimes:
        - nodejs12.x
        - nodejs10.x
      RetentionPolicy: Retain

#Lambda
  ElasticSearchSyncLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../output
      Handler: dynamodb-to-elasticsearch.handler
      Layers:
        - !Ref ElasticSearchSyncLambdaLayer
      Policies:
        - AmazonDynamoDBFullAccess
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - es:ESHttpPut
                - es:ESHttpPost
                - es:ESHttpGet
                - es:ESHttpDelete
              Resource: !Join ["/", [!GetAtt ElasticSearchUserDomain.Arn, "*"]]
      Events:
        DDBEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBUserTable.StreamArn
            StartingPosition: TRIM_HORIZON
      Environment:
        Variables:
          esUrl: !GetAtt ElasticSearchUserDomain.DomainEndpoint

  UserSearchLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../output
      Handler: user-search.handler
      Layers:
        - !Ref ElasticSearchSyncLambdaLayer
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - es:ESHttpPut
                - es:ESHttpPost
                - es:ESHttpGet
                - es:ESHttpDelete
              Resource: !Join ["/", [!GetAtt ElasticSearchUserDomain.Arn, "*"]]
      Environment:
        Variables:
          esUrl: !GetAtt ElasticSearchUserDomain.DomainEndpoint

  LambdaAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: allow-access-to-lambda-from-appsync
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: lambda:invokeFunction
                Resource:
                  - !GetAtt UserSearchLambda.Arn
                  - !Join ['', [!GetAtt UserSearchLambda.Arn, ':*']]

#GraphQL API
  UserGraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: Superformula User API
      AuthenticationType: API_KEY

  UserGraphQLApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt UserGraphQLApi.ApiId

  UserGraphQLApiSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt UserGraphQLApi.ApiId
      DefinitionS3Location: "./user.graphql"

  UserTableDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt UserGraphQLApi.ApiId
      Name: sf_users
      Description: "The Notes Table AppSync Data Source"
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt DynamoDBRole.Arn
      DynamoDBConfig:
        TableName: !Ref DynamoDBUserTable
        AwsRegion: us-east-2

  UserSearchLambdaDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt UserGraphQLApi.ApiId
      Name: user_search
      Type: AWS_LAMBDA
      LambdaConfig:
        LambdaFunctionArn: !GetAtt UserSearchLambda.Arn
      ServiceRoleArn: !GetAtt LambdaAccessRole.Arn

#GraphQL Resolvers
  GetUsersQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: UserGraphQLApiSchema
    Properties:
      ApiId: !GetAtt UserGraphQLApi.ApiId
      TypeName: Query
      FieldName: users
      DataSourceName: !GetAtt UserSearchLambdaDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "Invoke",
          "payload": $utils.toJson($ctx.args)
        }
      ResponseMappingTemplate: $util.toJson($ctx.result)

  GetUserQueryResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: UserGraphQLApiSchema
    Properties:
      ApiId: !GetAtt UserGraphQLApi.ApiId
      TypeName: Query
      FieldName: user
      DataSourceName: !GetAtt UserTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "GetItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          }
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  CreateUserMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: UserGraphQLApiSchema
    Properties:
      ApiId: !GetAtt UserGraphQLApi.ApiId
      TypeName: Mutation
      FieldName: createUser
      DataSourceName: !GetAtt UserTableDataSource.Name
      RequestMappingTemplate: |
        #set($ctx.args.user.createdAt = $util.time.nowISO8601())
        {
          "version": "2017-02-28",
          "operation": "PutItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($util.autoId())
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.user)
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

  UpdateUserMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: UserGraphQLApiSchema
    Properties:
      ApiId: !GetAtt UserGraphQLApi.ApiId
      TypeName: Mutation
      FieldName: updateUser
      DataSourceName: !GetAtt UserTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "UpdateItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          },
          "update": {
            "expression": "SET #username = :name, dob = :dob, address = :address, description = :description, updatedAt = :updatedAt",
            "expressionValues": {
              ":name": $util.dynamodb.toDynamoDBJson($ctx.args.user.name),
              ":dob": $util.dynamodb.toDynamoDBJson($ctx.args.user.dob),
              ":address": $util.dynamodb.toDynamoDBJson($ctx.args.user.address),
              ":description": $util.dynamodb.toDynamoDBJson($ctx.args.user.description),
              ":updatedAt": $util.dynamodb.toDynamoDBJson($util.time.nowISO8601())
            },
            "expressionNames": {
              "#username": "name"
            }
          },
          "condition": {
            "expression": "attribute_exists(id)"
          }
        }
      ResponseMappingTemplate: |
        #if ( $ctx.error &&  $ctx.error.type.equals("DynamoDB:ConditionalCheckFailedException"))
          #return
        #else
          $util.toJson($ctx.result)
        #end

  DeleteUserMutationResolver:
    Type: "AWS::AppSync::Resolver"
    DependsOn: UserGraphQLApiSchema
    Properties:
      ApiId: !GetAtt UserGraphQLApi.ApiId
      TypeName: Mutation
      FieldName: deleteUser
      DataSourceName: !GetAtt UserTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "DeleteItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          }
        }
      ResponseMappingTemplate: "$util.toJson($ctx.result)"

Outputs:
  APIKey:
    Description: API Key
    Value: !GetAtt UserGraphQLApiKey.ApiKey

  GraphQL:
    Description: GraphQL URL
    Value: !GetAtt UserGraphQLApi.GraphQLUrl